Add styled request_sudo function for initial password prompt

diff --git a/.chezmoiscripts/run_once_before_00-install-aur-helper.sh.tmpl b/.chezmoiscripts/run_once_before_00-install-aur-helper.sh.tmpl
--- a/.chezmoiscripts/run_once_before_00-install-aur-helper.sh.tmpl
+++ b/.chezmoiscripts/run_once_before_00-install-aur-helper.sh.tmpl
@@ -16,8 +16,8 @@ source "$LIB_DIR/.lib-common.sh"
 readonly AUR_HELPER="paru"
 
 main() {
-  if ! keep_sudo_alive; then
-    die "Failed to keep sudo alive"
+  if ! request_sudo; then
+    die "Failed to obtain sudo access"
   fi
 
   print_box "AUR Helper & Chaotic AUR"
diff --git a/.chezmoiscripts/run_onchange_before_10-install-package.sh.tmpl b/.chezmoiscripts/run_onchange_before_10-install-package.sh.tmpl
--- a/.chezmoiscripts/run_onchange_before_10-install-package.sh.tmpl
+++ b/.chezmoiscripts/run_onchange_before_10-install-package.sh.tmpl
@@ -22,8 +22,8 @@ packages+=({{- . | quote -}})
 {{ end }}
 
 main() {
-  if ! keep_sudo_alive; then
-    die "Failed to keep sudo alive"
+  if ! request_sudo; then
+    die "Failed to obtain sudo access"
   fi
 
   if ! command -v paru &>/dev/null; then
